<?php

namespace App\Modules\System\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Modules\System\Models\User;
use App\Services\TenantService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class AuthController extends Controller
{
    public function __construct(
        protected TenantService $tenantService
    ) {}

    public function showLoginForm()
    {
        return view('auth.login');
    }

    public function login(Request $request)
    {
        $loginField = $request->input('login');

        Log::info('[AuthController] LOGIN ATTEMPT', [
            'login_field' => $loginField,
            'remember' => $request->boolean('remember'),
        ]);

        // Validate the login request
        $request->validate([
            'login' => ['required', 'string'],
            'password' => ['required', 'string'],
        ]);

        // Find user by email OR username using Eloquent
        // No need to check for @ symbol - search both fields
        $user = User::where('email', $loginField)
                    ->orWhere('username', $loginField)
                    ->first();

        Log::info('[AuthController] USER SEARCH RESULT', [
            'login_field' => $loginField,
            'user_found' => $user ? true : false,
            'found_user_id' => $user?->id,
            'found_username' => $user?->username,
            'found_email' => $user?->email,
        ]);

        if (!$user) {
            Log::info('[AuthController] LOGIN FAILED - User not found', [
                'login_field' => $loginField,
            ]);
            return back()->withErrors([
                'login' => __('auth.failed'),
            ])->onlyInput('login');
        }

        // Attempt authentication using the user's email (always use email for Auth::attempt)
        // NOTE: Auth::attempt() internally regenerates the session ID for security
        // DO NOT call $request->session()->regenerate() before this - it causes CSRF mismatch!
        if (!Auth::attempt([
            'email' => $user->email,
            'password' => $request->password
        ], $request->boolean('remember'))) {
            Log::info('[AuthController] LOGIN FAILED - Invalid password', [
                'user_id' => $user->id,
                'login_field' => $loginField,
            ]);
            return back()->withErrors([
                'login' => __('auth.failed'),
            ])->onlyInput('login');
        }

        // Session is already regenerated by Auth::attempt()
        // No need to call regenerate() again - it would cause CSRF token mismatch!

        // Refresh user from database to ensure we have latest data
        $user = Auth::user();
        $request->session()->regenerate(); // Keep this for security, Auth::attempt() did it but we want fresh token
        $user->recordLogin($request->ip());
        $user->logActivity('Logged in', 'auth', 'login');

        Log::info('[AuthController] LOGIN SUCCESS', [
            'user_id' => $user->id,
            'email' => $user->email,
            'username' => $user->username,
            'is_developer' => $user->is_developer,
            'company_role' => $user->company_role,
            'company_id' => $user->company_id,
        ]);

        // Set tenant in service
        $this->tenantService->setCurrentTenant($user->tenant);

        // Determine redirect destination
        // IMPORTANT: Clear any invalid intended URLs (API/AJAX endpoints)
        // before redirecting to prevent redirect loops
        $this->clearInvalidIntendedUrls($request->session());

        Log::info('[AuthController] User is NOT developer - redirecting to dashboard');
        // Regular tenant → redirect to main dashboard
        // Always use explicit route, not intended() to avoid API endpoint redirects
        return redirect()->to(route('beranda'));
    }

    /**
     * Clear invalid intended URLs from session to prevent redirect loops.
     *
     * This prevents users from being redirected to API/AJAX endpoints
     * like /notifications/unread-count after login.
     */
    protected function clearInvalidIntendedUrls($session): void
    {
        $intendedUrl = $session->get('url.intended');

        if (!$intendedUrl) {
            return;
        }

        // Check if the intended URL is a valid HTML page or an API/AJAX endpoint
        $path = parse_url($intendedUrl, PHP_URL_PATH) ?? '';

        // API/AJAX endpoints that should NEVER be used as intended redirect
        $invalidPatterns = [
            'notifications/unread-count',
            'notifications/dropdown',
            'api/',
            'ajax/',
            '/unread-count',
            '/dropdown',
        ];

        foreach ($invalidPatterns as $pattern) {
            if (str_contains($path, trim($pattern, '/'))) {
                Log::info('[AuthController] Clearing invalid intended URL: ' . $path);
                $session->forget('url.intended');
                return;
            }
        }
    }

    public function logout(Request $request)
    {
        $user = auth()->user();

        if ($user) {
            $user->logActivity('Logged out', 'auth', 'logout');
        }

        Auth::logout();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('login');
    }
}
